# Generated by Django 4.2.6 on 2024-01-19 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_article_image_alter_article_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='title',
            new_name='name',
        ),
    ]
