# Generated by Django 4.2.6 on 2024-01-19 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0013_remove_article_category_article_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='categories', to='post.category'),
        ),
        migrations.AlterField(
            model_name='article',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='tags', to='post.tag'),
        ),
    ]
