# Generated by Django 4.2.6 on 2024-01-20 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0015_image_article_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='title',
        ),
    ]
