# Generated by Django 4.2.6 on 2024-01-21 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0019_remove_article_image_article_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='images',
        ),
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='article/'),
        ),
    ]
