# Generated by Django 4.2.6 on 2024-01-21 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0020_remove_article_images_article_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='image',
            new_name='images',
        ),
    ]
