# Generated by Django 4.2.6 on 2024-01-21 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0021_rename_image_article_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='images',
            new_name='image',
        ),
    ]
