# Generated by Django 4.2.6 on 2024-01-21 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0024_remove_article_image_article_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articleimage',
            name='article',
        ),
        migrations.RemoveField(
            model_name='article',
            name='image',
        ),
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ManyToManyField(blank=True, related_name='article_images', to='post.articleimage'),
        ),
    ]
