# Generated by Django 4.2.6 on 2024-01-21 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0025_remove_articleimage_article_remove_article_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleimage',
            name='article',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='post.article'),
            preserve_default=False,
        ),
    ]
