# Generated by Django 4.2.6 on 2024-01-21 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0027_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='artile',
            new_name='article',
        ),
    ]
