# Generated by Django 4.2.6 on 2024-01-23 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0029_comment_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='answer',
        ),
    ]
